config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'disasters#index'
  resources :disasters do
    member do
      post :comment
    end
  end
  resources :info

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :disaster
end

app/models/disaster.rb
class Disaster < ActiveRecord::Base
  validates_presence_of :info_id
  # 如果沒有驗證，index 裡的 disaster.info.name 就會壞掉

  belongs_to :user
  belongs_to :info
  has_many :comments
end

app/models/info.rb
class Info < ActiveRecord::Base

  belongs_to :user
  has_many :disasters
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :disasters
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/disasters_controller.rb
class DisastersController < ApplicationController
  before_action :authenticate_user!
  # 如果沒有驗證，create 裡的 current_user.disasters 就會抓不到東西而壞掉

  def index
    @disasters = Disaster.paginate(page: params[:page], per_page: 3)

  end

  def new
    @disaster = Disaster.new
  end

  def create
    # @disaster = Disaster.new(disaster_params)
    @disaster = current_user.disasters.new(disaster_params)
    if @disaster.save
      redirect_to disasters_path
    else
      render :new
    end
  end

  def show
    @disaster = Disaster.find(params[:id])
    @comments = @disaster.comments
    @comment = Comment.new
  end

  def edit
    @disaster = Disaster.find(params[:id])
  end

  def update
    @disaster = Disaster.find(params[:id])
    if @disaster.update(disaster_params)
      redirect_to disasters_path
    else
      render :edit
    end
  end

  def destroy
    @disaster = Disaster.find(params[:id])
    if @disaster.destroy
      redirect_to disasters_path
    else
      render :index
    end
  end

  def comment
    @disaster = Disaster.find(params[:id])
    @comment = Disaster.find(params[:id]).comments.new(comment_params)
    @comment.save
    redirect_to disaster_path(@disaster)
  end

  private

  def disaster_params
    params.require(:disaster).permit(:name, :description, :info_id)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disasters_helper.rb
module DisastersHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key,value| %>
    <div class="alert alert-dismissible alert-<%= flash_class(key) %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Alpha Camp
        <br>Design by
        <a href="#">Lupochia</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">冦盯災情資訊網</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                <li><%= link_to("註冊", new_user_registration_path) %></li>
                <li><%= link_to("登入", new_user_session_path) %></li>
              <% else %>
                 <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    HI!!!, <%= current_user.email %>
                    <b class="caret"></b>
                  </a>


                  <ul class="dropdown-menu" role="menu" aria-labelledby="">
                    <li><%= link_to("登出", destroy_user_session_path, method: :delete) %></li>
                  </ul>
                </li>
              <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/disasters/edit.html.erb
<!-- 這裡需要加錯誤訊息，否則驗證沒通過時 user 體驗會卡住 -->

<%= simple_form_for @disaster do |f| %>
  <div class="form-group">
    <%= f.input :name , input_html:{class: "form-control"} %>
    <%= f.input :description , input_html:{class: "form-control"} %>
    <br>請選擇分類：<br>
    <%= f.collection_select( :info_id, Info.all, :id, :name, prompt: true) %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting....."} %>
<% end %>

app/views/disasters/index.html.erb
<div class="row text-center">
<%= link_to("Create",new_disaster_path,class:"btn btn-warning ") %>
<br><br><br>
</div>
<div class="row">
  <% @disasters.each do |disaster| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption text-center">
        <h1><%= disaster.info.name %></h1>
        <h3><%= link_to disaster.name,disaster_path(disaster) %></h3>
        <br>張貼時間:
        <p><%= disaster.created_at  %></p>
        <p>
        <%= link_to("Show",disaster_path(disaster), class: "btn btn-primary") %>
        <% if current_user && current_user == disaster.user %>
            <%= link_to("Edit",edit_disaster_path(disaster), class: "btn btn-info") %>
            <%= link_to("Delete",disaster_path(disaster),method: :delete, data:{confirm: "Are U sure??"}, class: "btn btn-warning") %>
        <% end %>
        </p>
      </div>
    </div>
  </div>
  <% end %>

</div>
<div class="text-center">
  <%= will_paginate @disasters %>
</div>

app/views/disasters/new.html.erb
<!-- 這裡需要加錯誤訊息，否則驗證沒通過時 user 體驗會卡住 -->

<%= simple_form_for @disaster do |f| %>
  <div class="form-group">
    <%= f.input :name , input_html:{class: "form-control"} %>
    <%= f.input :description , input_html:{class: "form-control"} %>
    <br>請選擇分類：<br>
    <%= f.collection_select( :info_id, Info.all, :id, :name, prompt: true) %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting....."} %>
<% end %>

app/views/disasters/show.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>名稱</th>
      <th>詳細敘述</th>
      <th>date</th>
      <th>Creator</th>

    </tr>
  </thead>
  <tbody>
        <tr>
          <td><%= @disaster.name %></td>
          <td><%= @disaster.description %></td>
          <td><%= @disaster.created_at %></td>
          <td><%= @disaster.user.email %></td>
        </tr>
  </tbody>
</table>
<div class="container text-center" >
  <!-- <div  style="border: 1px solid blue; width: 30%;"> -->
          <h3>留言</h3>
          <br>
          <table class="table table-bordered table-hover">
            <tbody>
              <% @comments.each do |comment| %>
                  <tr>

                      <td><%= comment.content %></td>

                  </tr>
                  <% end %>
            </tbody>
          </table>
          <%= simple_form_for @comment, url: comment_disaster_path do |f| %>
            <div class="form-group">
              <%= f.input :content , input_html:{class: "form-control"} %>
            </div>
            <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting....."} %>
          <% end %>

  </div>
</div>

<br>
<div class="text-center">
<%= link_to "回上一頁",disasters_path, class: "btn btn-primary" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DisasterSupport</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class="container">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
    <%= render "common/footer" %>


  </body>
</html>